# =========================
# Configuration syntax
# =========================
#
# Initial spaces will be ignored.
#
# Comments are preceded by an hash (#) and can be inlined.
#
# Each section must be defined by an UUID (v4) and can contains the following
# fields:
#     - title          String           Required
#     - description    String           Optional
#     - position       Array[Number]    Required
#     - connections    Array[UUID]      Optional
# The section ends when an UUID is encountered or EOF is reached.
#
# The value ends when a newline is encountered or EOF is reached.
#
# Multi-line strings can be defined with the following syntax:
#     - >    Does NOT preserve newlines
#     - |    Does preserve newlines
# Initial and final spaces will be ignored.
# The string ends when the indentation changes or EOF is reached.
#
# Arrays can be defined as a list of values delimited by a comma (,) and
# enclosed by square brackets ([]) or by listing every entry in a newline
# preceded by a dash (-).

# =========================
# Example configuration
# =========================

c79b4316-7236-45ca-ab1b-d5bd8b78a484:
    title: this is a title
    description: >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec
        commodo dui. Mauris eu risus et libero pulvinar facilisis. In
        commodo imperdiet mauris, vel hendrerit dolor ultricies quis.
        Vivamus varius tellus sed libero fringilla ultrices. Maecenas at
        ipsum sit amet mauris finibus accumsan. In congue consectetur dui.
        Nam id fermentum orci.
    position: [0, 0]
    connections: # no repetitions allowed
        - c79b4316-7236-45ca-ab1b-d5bd8b78a485
        - c79b4316-7236-45ca-ab1b-d5bd8b78a486

c79b4316-7236-45ca-ab1b-d5bd8b78a485:
    title: this is a title
    description: >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec
        commodo dui. Mauris eu risus et libero pulvinar facilisis. In
        commodo imperdiet mauris, vel hendrerit dolor ultricies quis.
        Vivamus varius tellus sed libero fringilla ultrices. Maecenas at
        ipsum sit amet mauris finibus accumsan. In congue consectetur dui.
        Nam id fermentum orci.
    position: [1200, 0]

c79b4316-7236-45ca-ab1b-d5bd8b78a486:
    title: this is a title
    description: >
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec
        commodo dui. Mauris eu risus et libero pulvinar facilisis. In
        commodo imperdiet mauris, vel hendrerit dolor ultricies quis.
        Vivamus varius tellus sed libero fringilla ultrices. Maecenas at
        ipsum sit amet mauris finibus accumsan. In congue consectetur dui.
        Nam id fermentum orci.
    position: [600, 250]
    connections:
        - c79b4316-7236-45ca-ab1b-d5bd8b78a485
